/* Step B: a second 2-descent (4-coverings) on E_{a,b} to find large generators.

   E: Y^2 = X(X - e2)(X - e3).  The 2-covering of the Kummer class (d1, d2), d3 = core(d1 d2):
        d1 u1^2 - d2 u2^2 = e2 t^2,     d1 u1^2 - d3 u3^2 = e3 t^2,     X = d1 u1^2 / t^2.
   1. Parametrise the conic d1 u1^2 - d2 u2^2 - e2 t^2 = 0:  (u1, u2, t) = (q1, q2, q3)(r, s).
      Then  d3 u3^2 = d1 q1^2 - e3 q3^2,  and  d1 d3 u3^2 = A^2 - D (c q3)^2  with A = d1 q1,
      d1 e3 = c^2 D, D squarefree.
   2. D != 1: in L = Q(sqrt D),  A - c q3 sqrt(D) = mu (z0 + z1 sqrt D)^2,  mu in L(S,2) with
      N(mu) = d1 d3 mod squares.  Comparing coefficients (mu = m0 + m1 sqrt D):
          A        = m0 (z0^2 + D z1^2) + 2 m1 D z0 z1
          -c q3    = m1 (z0^2 + D z1^2) + 2 m0 z0 z1
      D = 1: A - c q3 = mu z^2, A + c q3 = mu' w^2 with mu mu' = d1 d3 mod squares, mu in Q(S,2).
      Either way: two quadrics in P^3, a 4-covering.
   3. Quartic model: a rational singular member Q1 - lam Q2 of the pencil (rank 3, a cone), its
      conic parametrised by p, the lines through the vertex cut Q2 in two points: the discriminant
      is a quartic g(p), searched with hyperellratpoints after minimising and reducing.
   4. A point gives (r : s), hence (u1 : u2 : t) and X = d1 u1^2 / t^2 on E.

   STATUS (2026-10-02): INCOMPLETE, the quartic model of step 3 does not exist over Q here. On 43:9
   (class (1,-1): D = 1930, 12 generators of L(S,2), 128 mu pass the norm filter) det(Q1 - l Q2)
   factors into two quadratics for every mu, so the pencil has no rational singular member: the
   cones are defined over quadratic fields only. A working 4-descent must construct the quartic
   model from a conjugate pair of cones (as in Merriman-Siksek-Smart). Steps 1-2 and ks2() are
   tested; use route_d_isocoset.gp instead for now.                                            */

\r route_d_cosetsearch.gp

/* symmetric matrix of a quadratic form f in the variables V */
qfmat(f, V) = matrix(#V, #V, i, j, deriv(deriv(f, V[i]), V[j]) / 2);
qfval(M, v) = (v~ * M * v)[1, 1];

/* quartic model of the intersection of quadrics M1, M2 (4x4) and the map back to P^3.
   Returns [] or [g, B, k, wt, M2] with g(p) the quartic, wt(p) the 4-vector on the cone,
   k the vertex; for a point (p, y) of y^2 = g(p): v = wt(p) + tau k, tau = (-b +- y) / Q2(k). */
quarticmodel(M1, M2) =
{
  my(P = matdet(M1 - 'l*M2), lam = [], cands = List());
  if(P == 0, return([]));
  my(f = factor(P)[, 1]);
  for(i = 1, #f, if(poldegree(f[i]) == 1, listput(cands, -polcoeff(f[i], 0) / polcoeff(f[i], 1))));
  foreach(cands, la,
    my(Ms = M1 - la*M2, K = matker(Ms));
    if(#K != 1, next);
    my(k = K[, 1], B = matsupplement(Mat(k)), Mp = B~ * Ms * B, C = Mp[2..4, 2..4]);
    my(sol = qfsolve(C));
    if(type(sol) != "t_COL", next);                     /* this cone has no rational conic point */
    my(Pm = qfparam(C, sol), w3 = Pm * ['p^2, 'p, 1]~, wt = B * concat([0], w3));
    my(q2k = qfval(M2, k), bb = (k~ * M2 * wt)[1, 1], cc = qfval(M2, wt));
    if(q2k == 0, next);
    my(g = bb^2 - q2k * cc);
    if(poldegree(g) < 3 || !issquarefree(g), next);
    return([g, B, k, wt, M2, q2k, bb]));
  [];
}

/* points of the 4-covering (quadrics M1, M2 in (r, s, z0, z1)) -> points of P^3 */
fourpoints(M1, M2, H) =
{
  my(Qm = quarticmodel(M1, M2), out = List());
  if(Qm == [], return([]));
  my([g, B, k, wt, M2_, q2k, bb] = Qm);
  my(gi = g * denominator(content(g))^2); my(cg = content(gi)); gi = gi / (cg / core(cg));
  my(m1, m2, gm = hyperellminimalmodel(gi, &m1), gr = hyperellred(gm, &m2));
  if(type(gr) == "t_VEC", gr = gr[1] + gr[2]^2/4);
  my(pts = iferr(hyperellratpoints(gr, H), err, []));
  foreach(pts, pt,
    my(x1 = mobius(m2, pt[1])); if(x1 == "inf", next);
    my(p0 = mobius(m1, x1)); if(p0 == "inf", next);
    my(w = subst(wt, 'p, p0), b0 = subst(bb, 'p, p0), g0 = subst(g, 'p, p0), y);
    if(!issquare(g0, &y), next);
    foreach([y, -y], yy, my(tau = (-b0 + yy) / q2k, v = w + tau*k);
      if(qfval(M2_, v) != 0, error("fourpoints: point not on Q2"));
      if(qfval(M1, v) != 0, error("fourpoints: point not on Q1"));
      listput(out, v)));
  Vec(out);
}

/* L(S,2) for L = Q(sqrt D): enlarge S (prime ideals above the primes in PS) by small primes until
   the S-class group has odd order; then L(S,2) is generated by the torsion unit, the fundamental
   units and the S-units.  Returns [bnf, basis as polmods]. */
ks2(D, PS) =
{
  my(bnf = bnfinit('y^2 - D, 1), ps = Set(PS), U, p = 2);
  for(it = 1, 50,
    my(S = concat(apply(q -> idealprimedec(bnf, q), ps)));
    U = bnfsunit(bnf, S);
    if(U[5][1] % 2, break);
    while(setsearch(ps, p), p = nextprime(p + 1));
    ps = setunion(ps, [p]));
  if(U[5][1] % 2 == 0, error("ks2: S-class group stays even"));
  my(md = 'y^2 - D, gens = concat([Mod(bnf.tu[2], md)], apply(u -> Mod(u, md), bnf.fu)));
  gens = concat(gens, apply(u -> Mod(u, md), U[1]));
  [bnf, gens];
}

/* the 4-coverings of the 2-covering of class (d1, d2) of E = [0, e2, e3]; points mapped to E */
fourdescent_class(e2, e3, d1, d2, H, maxmu = 4096) =
{
  my(d3 = core(d1*d2), Qc = matdiagonal([d1, -d2, -e2]), sol = qfsolve(Qc), out = List(), V = ['r, 's, 'z0, 'z1]);
  if(type(sol) != "t_COL", return([]));
  my(Mp = qfparam(Qc, sol), qv = Mp * ['r^2, 'r*'s, 's^2]~, q1 = qv[1], q3 = qv[3]);
  my(A = d1*q1, D = core(d1*e3), c = sqrtint(d1*e3 / D));
  if(c^2 * D != d1*e3, error("fourdescent: d1 e3 = c^2 D fails"));
  my(PS = Set(concat([2], concat(apply(n -> if(abs(n) > 1, factor(abs(n))[, 1]~, []),
          [D, c, d1, d2, d3, e2, e3, e3 - e2, numerator(matdet(Mp)), denominator(matdet(Mp))])))));
  my(cands = List());
  if(D == 1,
    my(B = concat([-1], PS));
    forvec(x = vector(#B, i, [0, 1]), my(mu = prod(i = 1, #B, B[i]^x[i]), mu2 = core(d1*d3*mu));
      listput(cands, [(A - c*q3) - mu*'z0^2, (A + c*q3) - mu2*'z1^2])),
    my(K = ks2(D, PS), G = K[2], nG = #G);
    if(2^nG > maxmu * 64, return([]));
    forvec(x = vector(nG, i, [0, 1]), my(mu = prod(i = 1, nG, G[i]^x[i]), nm = norm(mu));
      if(!issquare(nm / (d1*d3)), next);
      my(lm = lift(mu), m0 = polcoeff(lm, 0, 'y), m1 = polcoeff(lm, 1, 'y));
      listput(cands, [A - (m0*('z0^2 + D*'z1^2) + 2*m1*D*'z0*'z1), -c*q3 - (m1*('z0^2 + D*'z1^2) + 2*m0*'z0*'z1)])));
  if(#cands > maxmu, cands = cands[1..maxmu]);
  foreach(cands, F,
    my(M1 = qfmat(F[1], V), M2 = qfmat(F[2], V));
    foreach(fourpoints(M1, M2, H), v,
      my(r0 = v[1], s0 = v[2]);
      if(r0 == 0 && s0 == 0, next);
      my(u1 = substvec(q1, ['r, 's], [r0, s0]), t = substvec(q3, ['r, 's], [r0, s0]));
      if(t == 0, next);
      my(X = d1*u1^2/t^2, Y2 = X*(X - e2)*(X - e3), Y);
      if(!issquare(Y2, &Y), error("fourdescent: point does not lift to E at class ", [d1, d2]));
      listput(out, [X, Y])));
  Vec(out);
}
