"""Refined random model: for each prime l, the allowed fraction WITHIN the image of
E(Q) (generators + torsion) in E(F_l), instead of over all of E(F_l).  Rational
points can only reduce into that image, so this is the honest independence benchmark."""
import sys, ast, math, io, contextlib
from route_d_mwsieve import run

def image_fracs(path):
    out = {}
    for line in open(path):
        l, c1, c2, rest = line.strip().split(" ", 3)
        co, bits = rest.rsplit(" ", 1)
        l, c1, c2, co = int(l), int(c1), int(c2), ast.literal_eval(co)
        S = {(0, 0)}; frontier = [(0, 0)]
        while frontier:                      # closure of the subgroup generated by the coordinates
            x = frontier.pop()
            for g in co:
                y = ((x[0] + g[0]) % c1, (x[1] + g[1]) % c2)
                if y not in S:
                    S.add(y); frontier.append(y)
        allowed = sum(bits[b * c1 + a] == "1" for a, b in S)
        out[l] = (len(S), c1 * c2, allowed / len(S), bits.count("1") / len(bits))
    return out

if __name__ == "__main__":
    tag, r = sys.argv[1], int(sys.argv[2])
    chain = [8, 24, 48, 240, 1680, 5040]
    stats = []
    with contextlib.redirect_stdout(io.StringIO()):
        cls, hist = run(f"sieve_data_{tag}.txt", r, 2, chain, stats=stats)
    fr = image_fracs(f"sieve_data_{tag}.txt")
    Nd = hist[-1][0]
    full = img = 1.0
    for (N, l, c1, c2, frac, nb, na) in stats:
        full *= fr[l][3]; img *= fr[l][2]
    tot = 4 * Nd**r
    print(f"{tag}: died at N={Nd} ({tot} classes). expected survivors, full-group model: {tot*full:.3g};  image-restricted model: {tot*img:.3g}")
    small = [(l, fr[l][0], fr[l][1], round(fr[l][2], 3)) for (N, l, *_ ) in stats if fr[l][0] < fr[l][1]]
    print("   primes where the image is a proper subgroup (l, |image|, |E(F_l)|, allowed frac in image):", small[:8])
